import express from 'express';

import tasks from './tasks.router'

/**
 * @swagger
 * components:
 *  schemas:
 *      Task:
 *       type: object
 *       required:
 *          -title
 *       properties:
 *          id:
 *              type: string
 *              description: The auto-generated MongoDB ObjectId of the task
 *              pattern: '^[a-fA-F0-9]{24}$'
 *              example: 60c72b2f9b1e8f5b3f0c4db0
 *          title:
 *              type: string
 *              description: The title of the task
 *              example: 'Task 1'
 *          state:
 *              type: boolean
 *              description: State of the task (e.g., true or false)
 *              example: false
 *          createdAt:
 *              type: string
 *              format: date-time
 *              description: The creation date of the task
 *              example: '2024-12-28T12:00:00Z'
 *          updatedAt:
 *              type: string
 *              format: date-time
 *              description: The last updated date of the task
 *              example: '2024-12-28T12:30:00Z'
 *          __v:
 *              type: integer
 *              description: The version key (auto-generated by MongoDB)
 *              example: 0
 * 
 */

/**
 * @swagger
 * tags:
 *  name: Tasks
 *  description: The Task Managing API
 */


const router = express.Router()

export default (): express.Router => {
    tasks(router)
    return router;
};